import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toast";

import Navbar from "./_component/Navbar/Navbar";
import Footer from "./_component/Footer/Footer";
import FirstNav from "./_component/FirstNav/FirstNav";

const ExoFont = Exo({
  variable: "--font-Exo",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${ExoFont.className} antialiased`}>
      <body>
        <FirstNav />
        <Navbar />
        <div className="container mx-auto">{children}</div>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
